[package]
name = 'multicast-socket'
description = 'Single-socket multi-interface multicast socket'
version = "0.3.2"
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'
homepage = 'https://github.com/bltavares/multicast-socket'
repository = 'https://github.com/bltavares/multicast-socket'
readme = 'README.md'
license = 'MIT OR Apache-2.0'
keywords = ['multicast']

[dependencies]
get_if_addrs = '0.5.3'

[dependencies.socket2]
version = '0.3.19'
features = ['reuseport']

[target.'cfg(windows)'.dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_System_IO",
]

[target.'cfg(not(windows))'.dependencies.nix]
version = '0.19.1'

[target.'cfg(not(windows))'.dependencies.libc]
version = '0.2.85'
